hub:
  image: selenium/hub
  ports:
    - "4444:4444"
firefox:
  image: selenium/node-firefox
  links:
    - hub
  environment:
   SCREEN_WIDTH: 1366
   SCREEN_HEIGHT: 768
chrome:
  image: selenium/node-chrome
  links:
    - hub
  environment:
   SCREEN_WIDTH: 1366
   SCREEN_HEIGHT: 768
